### ISSUE TITLE
kernel and bootloader sources, toolchains

### ISSUE THREAD

**Issue by rileyx** [kobolabs/Kobo-Arc#1]
Please provide the sources for kernel 3.0.31 stamped may 7, 2013 @ 17:11:07 and the associated toolchain, build scripts etc. 

I would also appreciate the sources and toolchain for the Arc bootloader. If there is more than one bootloader "in the wild" please provide instructions for determining which version is in a particular Arc as well.

Thanks.

**Comment by gtalusan** [comment]
Hi,

The toolchain is CodeSourcery 2010q1 and there is a build script in kernel.tgz package that shows you how to build the kernel.  Pass in "zeus" as the first parameter on the command line.

The bootloader isn't open source.

I will update the kernel tarball shortly so that it lines up with the latest May 7 release.

**Comment by rileyx** [comment]
Thanks for the kernel sources. Is there more than one bootloader in use? When I connect to my arc with fastboot, I can do this, which looks like I am talking to uboot: (which is GPL afaik)

> fastboot getvar version
> version: 0.5
> finished. total time: 0.004s
> 
> fastboot getvar version-bootloader
> version-bootloader: ZEUSXX03
> finished. total time: 0.004s
> 
> fastboot getvar secure
> secure: HS
> finished. total time: 0.005s
> 
> fastboot getvar product
> product: zeus
> finished. total time: 0.003s
> 
> fastboot getvar serialno
> serialno: xxxxxxxxxxxxx
> finished. total time: 0.008s

Thanks.

**Comment by gtalusan** [comment]
Hi,

There are two bootloaders in play here - see the OMAP reference design.  We were using U-Boot as the secondary bootloader but it was to have been switched out for something properietary.

Let me follow up internally.  It may take some time for a response.

**Comment by rileyx** [comment]
I understand. Thanks for getting back so quickly. When you are checking out whether or not the arc is using uboot, could you also find out if the first stage boot-loader is x-loader? If so, could you please provide those sources as well?

Thanks

**Comment by rileyx** [comment]
sorry about the close

**Comment by gtalusan** [comment]
The first stage bootloader is x-loader.  I've placed the source code online.

Please keep in mind that the binaries are signed.

**Comment by rileyx** [comment]
Will do. Thanks.

**Comment by rileyx** [comment]
Any progress with the uboot question? Thanks.

**Comment by gtalusan** [comment]
Wheels are in motion.

**Comment by rileyx** [comment]
Uhoh... I hope that doesn't mean there is uncertainty about the code that was used to compile the boot-loader. It's never good when that happens.

Regardless, thanks for your efforts.

**Comment by rileyx** [comment]
Are the wheels still in motion? How much longer do you think this will take?

**Comment by gtalusan** [comment]
Yes.  Sit tight.

**Comment by gtalusan** [comment]
There was movement two months ago.
